services:
    - type: web
      name: dash-rga-snolab
      env: python
      plan: free
      buildCommand: "pip install -r requirements.txt"
      startCommand: "gunicorn dash-rga-snolab:server"
      envVars:
        - key: PYTHON_VERSION
          value: 3.8.15
